# Generated by Django 2.2.1 on 2019-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.CharField(max_length=20)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('Nombres', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
        ),
    ]
